apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/kagent-dev/kagent/helm
    targetRevision: 0.10.1
    chart: kagent
    helm:
      values: |
        tag: "0.10.1"
        controller:
          image:
            tag: "0.10.1"
        ui:
          image:
            tag: "0.10.1"
        istio-agent:
          enabled: false
        cilium-policy-agent:
          enabled: false
        cilium-manager-agent:
          enabled: false
        cilium-debug-agent:
          enabled: false
        helm-agent:
          enabled: false
        kgateway-agent:
          enabled: false
        observability-agent:
          enabled: false
        promql-agent:
          enabled: false
        argo-rollouts-agent:
          enabled: false
        providers:
          default: gemini
          gemini:
            model: gemini-2.5-flash-lite
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: kagent-gemini
    jsonPointers:
    - /data/GOOGLE_API_KEY
