apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/kagent-dev/kagent/helm
    targetRevision: 0.10.2
    chart: kagent
    helm:
      values: |
        tag: "0.10.2"
        otel:
          tracing:
            enabled: true
            exporter:
              otlp:
                endpoint: "http://phoenix-svc.phoenix.svc:4317"
                # endpoint: "http://otel-collector.mlflow.svc:4317"
        env:
          - name: OTEL_EXPORTER_OTLP_HEADERS
            value: "Authorization=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJBcGlLZXk6MSJ9.-sAfgB07jS_4naVQqmfT4SrwSD1mW8YdzljlQprlPOg"
          - name: OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT
            value: "SPAN_AND_EVENT"
        controller:
          image:
            tag: "0.10.2"
        ui:
          image:
            tag: "0.10.2"
        istio-agent:
          enabled: false
        cilium-policy-agent:
          enabled: false
        cilium-manager-agent:
          enabled: false
        cilium-debug-agent:
          enabled: false
        helm-agent:
          enabled: false
        kgateway-agent:
          enabled: false
        observability-agent:
          enabled: false
        promql-agent:
          enabled: false
        argo-rollouts-agent:
          enabled: false
        providers:
          default: gemini
          gemini:
            model: gemini-3.5-flash-lite
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: kagent-gemini
    jsonPointers:
    - /data/GOOGLE_API_KEY
  - group: ""
    kind: ConfigMap
    name: kagent-controller
    jsonPointers:
    - /data/OTEL_EXPORTER_OTLP_HEADERS
    - /data/OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT
