apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: opentelemetry-demo
  namespace: argocd
spec:
  destination:
    namespace: otel-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: opentelemetry-demo
    helm:
      values: "components:\n  accounting:\n    enabled: false\n  ad:\n    enabled:\
        \ false\n  agent:\n    enabled: false\n  astronomy-db:\n    enabled: false\n\
        \  cart:\n    enabled: false\n  chatbot:\n    enabled: false\n  checkout:\n\
        \    enabled: false\n  currency:\n    enabled: false\n  email:\n    enabled:\
        \ false\n  flagd:\n    enabled: false\n  fraud-detection:\n    enabled: false\n\
        \  frontend:\n    enabled: false\n  frontend-proxy:\n    enabled: false\n\
        \  image-provider:\n    enabled: false\n  kafka:\n    enabled: false\n  load-generator:\n\
        \    enabled: false\n    envOverrides:\n    - name: LOCUST_HEADLESS\n    \
        \  value: 'false'\n    service:\n      port: 8089\n  mcp:\n    enabled: false\n\
        \  opamp-server:\n    enabled: false\n  payment:\n    enabled: false\n  product-catalog:\n\
        \    enabled: false\n  quote:\n    enabled: false\n  recommendation:\n   \
        \ enabled: false\n  shipping:\n    enabled: false\n  telemetry-docs:\n   \
        \ enabled: false\n  valkey-cart:\n    enabled: false\ngrafana:\n  enabled:\
        \ false\njaeger:\n  allInOne:\n    resources:\n      requests:\n        memory:\
        \ 100Mi\n  enabled: true\nopensearch:\n  enabled: false\nopentelemetry-collector:\n\
        \  config:\n    exporters: {}\n    service:\n      pipelines:\n        traces:\n\
        \          exporters:\n          - otlp_grpc/jaeger\n          - debug\n \
        \         - span_metrics\nprometheus:\n  enabled: false\n"
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.41.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
