apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: substrate
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/kagent-dev/substrate/helm
    targetRevision: 0.0.9
    chart: substrate
  destination:
    server: https://kubernetes.default.svc
    namespace: ate-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
