apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: policy-retrieval-custom
  namespace: agentgateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: retrieval-routes
  backend:
    ai:
      defaults:
        - field: "model"
          value: "default-model-config"
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: policy-retrieval-official
  namespace: agentgateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: retrieval-routes
  backend:
    ai:
      defaults:
        - field: "model"
          value: "default-model-config"
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: policy-k8s-agent
  namespace: agentgateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: k8s-agent-routes
  backend:
    ai:
      defaults:
        - field: "model"
          value: "default-model-config"
