apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: agentregistry
  namespace: agentregistry
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: agentregistry
  to:
  - group: ""
    kind: Service
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: agentregistry
  namespace: agentregistry
spec:
  parentRefs:
  - name: agentgateway-external
    namespace: agentgateway-system
  hostnames:
  - "registry.localhost"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: agentregistry-inventory-api
      namespace: agentregistry
      port: 8080
