apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gateway-model-custom
  namespace: kagent
spec:
  provider: OpenAI
  model: "gemini-3.5-flash-lite"
  openAI:
    baseUrl: "http://agentgateway-external.agentgateway-system.svc.cluster.local/v1/retrieval/custom"
  apiKeyPassthrough: true
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gateway-model-official
  namespace: kagent
spec:
  provider: OpenAI
  model: "gemini-3.5-flash-lite"
  openAI:
    baseUrl: "http://agentgateway-external.agentgateway-system.svc.cluster.local/v1/retrieval/official"
  apiKeyPassthrough: true
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gateway-model-k8s
  namespace: kagent
spec:
  provider: OpenAI
  model: "gemini-3.5-flash-lite"
  openAI:
    baseUrl: "http://agentgateway-external.agentgateway-system.svc.cluster.local/v1/k8s"
  apiKeyPassthrough: true
